version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: encontrei-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: encontrei
      MYSQL_USER: user_encontrei
      MYSQL_PASSWORD: encontrei123@
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: